language: python

python:
    - "3.7"

cache: pip

install:
    - pip install -r requirements.txt
    - sudo pip install codecov

script:
    - pytest test.py -v --cov=./
    - pytest --flake8

after_success:
  - codecov
